CREATE TABLE "health_resources" (
	"id" serial PRIMARY KEY NOT NULL,
	"practice_id" integer,
	"title" text NOT NULL,
	"description" text,
	"content" text,
	"category" text NOT NULL,
	"type" text NOT NULL,
	"species" text DEFAULT 'all' NOT NULL,
	"thumbnail_url" text,
	"image_url" text,
	"video_url" text,
	"external_url" text,
	"download_url" text,
	"author" text,
	"tags" text,
	"estimated_read_time" text,
	"difficulty" text,
	"featured" boolean DEFAULT false NOT NULL,
	"is_public" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"view_count" text DEFAULT '0',
	"emergency_type" text,
	"contact_phone" text,
	"contact_address" text,
	"availability" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "health_resources" ADD CONSTRAINT "health_resources_practice_id_practices_id_fk" FOREIGN KEY ("practice_id") REFERENCES "public"."practices"("id") ON DELETE cascade ON UPDATE no action;